go_test(
    name = "gcp_test",
    srcs = [
        "gcp_test.go",
    ],
    data = [
        "//deploy/gcp:gcp_bin",
    ],
    deps = [
        "//third_party/go:terratest",
        "//third_party/go:stretchr_testify",
    ]
)
